### ISSUE TITLE
`creatorData` is an array of empty objects

### ISSUE THREAD

**Issue by cpiber** [parkeraddison/watch-on-nebula#1]
standard.tv might have changed their site, your extension doesn't work anymore.
The only element that has a meaningful dataset is the `.youtube-creator` itself, and it only has a `video` property (the channel id). There is no more title.

Possible solution is to change lines 17-19 in background_script.js to:
```js
        let creatorData = Array.from(creators).map(d => {
            return {
                video: d.dataset.video,
                title: d.querySelector('a').innerText
            }
        });
```

**Comment by parkeraddison** [comment]
Thank you! Yup, it's been broken for some weeks now. You motivated me to commit the changes I've had sitting on my laptop :)

Should be fixed by 38a72d31c161424eda3657db877a9befdb1a79c8.

The Firefox addon page has the updated version now.
