### ISSUE TITLE
Chrome support

### ISSUE THREAD

**Issue by cpiber** [parkeraddison/watch-on-nebula#3]
Hi! I'm the creator of https://github.com/cpiber/NebulaEnhance, and recently I've received a request to basically provide the functionality you do, since you don't have Chrome support (https://github.com/cpiber/NebulaEnhance/discussions/7).

In light of this I first wanted to ask if you plan on adding support. My extension is available in both browsers, so simply implementing it would mean stealing your extension's content.

**Comment by parkeraddison** [comment]
Hey @cpiber I appreciate that you checked in first -- go right ahead!

This code supports the mozilla-chrome polyfill if you need it. As I'm sure you've noticed the current state of the code is a bit outdated now, I originally *intended* to keep up with Nebula updates and improve the extension but alas life got in the way ;)

Have fun out there. I'll edit my readme to point to NebulaEnhance

**Comment by cpiber** [comment]
Thank you, this is very kind of you.

I can always offer you maintainer access to NebulaEnhance, I'd be happy to see you there!
